apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aspnetcore-config.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
